WITH TRIPS AS(
    select
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(TO_TIMESTAMP(STARTED_AT)) as TRIP_DATE,
    START_STATION_ID,
    END_STATION_ID,
    MEMBER_OR_CASUAL_RIDE AS NUMBER_CASUAL,
    TIMESTAMPDIFF(SECOND ,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECOND,
    TIMESTAMPDIFF(MINUTES ,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECOND

    from {{ source('demo', 'bike') }}
)

select
*
from TRIPS